name: Publish Python Package to TestPyPI

on:
  # Trigger the workflow only for tags pushed to the 'master' branch
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish:
    # Use the latest Ubuntu runner for the job
    runs-on: ubuntu-latest

    environment:
      # Set the environment to 'testpypi'
      name: testpypi

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Step 3: Install dependencies (pip, build, twine, and flake8)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine flake8

    # Step 4: Check PEP8 compliance on changed files
    - name: Check PEP8 compliance
      run: |
        # Get a list of changed files in the push
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Filter Python files and run flake8
        echo "$changed_files" | grep '\.py$' | xargs flake8

    # Step 5: Build the Python package
    - name: Build the package
      run: |
        python -m build

    # Step 6: List the contents of the build directory (dist/)
    - name: List build directory contents
      run: |
        ls -lh dist/  # List the contents of the 'dist' directory to verify the built files

    # Step 7: Upload the package to TestPyPI
    - name: Publish to TestPyPI
      env:
        # Use credentials stored in GitHub Secrets
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose  # Upload the built package to TestPyPI
